#!/usr/bin/env python3
"""
Learn Hunspell SFX rules from form→lemma pairs.

Usage: python3 learn_rules.py <forms.tsv> <output.aff>

Input: TSV with columns: form  lemma
Output: Hunspell .aff file with generated SFX rules
"""

import sys
import re
from collections import defaultdict

def strip_common_suffix(word, lemma):
    """Figure out what to strip from lemma and what to add to get form.
    Returns (strip, add) if lemma != form, else None."""
    if lemma == word:
        return None
    
    # Find common prefix
    min_len = min(len(lemma), len(word))
    common = 0
    for i in range(min_len):
        if lemma[i] != word[i]:
            break
        common = i + 1
    
    # What needs to be stripped from lemma after the common prefix
    lemma_suffix = lemma[common:]
    form_suffix = word[common:]
    
    return (lemma_suffix, form_suffix)

def main():
    tsv_path = sys.argv[1] if len(sys.argv) > 1 else "/tmp/all_forms.tsv"
    out_path = sys.argv[2] if len(sys.argv) > 2 else "/dev/stdout"
    
    pairs = []
    with open(tsv_path, encoding='utf-8') as f:
        for line in f:
            parts = line.strip().split('\t')
            if len(parts) == 2 and parts[0] != parts[1]:
                pairs.append((parts[0], parts[1]))
    
    print(f"Loaded {len(pairs)} form→lemma pairs", file=sys.stderr)
    
    # Group by (strip, add) pattern
    patterns = defaultdict(lambda: defaultdict(set))
    # key: (strip_suffix, add_suffix) -> dict: prefix_set -> {lemmas}
    
    for form, lemma in pairs:
        result = strip_common_suffix(form, lemma)
        if result is None:
            continue
        strip, add = result
        
        # Also track the character right before the stripped part (condition)
        cond = lemma[-len(strip) - 1] if len(strip) < len(lemma) else ""
        
        patterns[(strip, add)][cond].add(lemma)
    
    # Write output
    with open(out_path, 'w', encoding='utf-8') as f:
        f.write("# Generated Hunspell SFX rules to augment ru_RU.aff\n")
        f.write("# These rules cover word forms not generated by the original dictionary.\n")
        f.write(f"# Generated from {len(pairs)} form→lemma pairs\n")
        f.write("\n")
        
        # Assign flags: use numbers starting from 1000
        flag_num = 1000
        
        for (strip, add) in sorted(patterns.keys(), key=lambda x: -len(patterns[x])):
            conds = patterns[(strip, add)]
            
            # Count unique lemmas for this pattern
            all_lemmas = set()
            for lemmas in conds.values():
                all_lemmas.update(lemmas)
            
            if len(all_lemmas) < 5:
                continue  # skip rare patterns
            
            flag = str(flag_num)
            flag_num += 1
            
            f.write(f"SFX {flag} Y {len(conds)}\n")
            
            for cond, lemmas in sorted(conds.items(), key=lambda x: -len(x[1])):
                if len(lemmas) < 3:
                    continue
                if strip:
                    strip_part = strip
                else:
                    strip_part = "0"
                
                add_part = add if add else "0"
                cond_part = cond if cond else "."
                
                f.write(f"SFX {flag} {strip_part} {add_part} {cond_part}\n")
            
            f.write(f"\n")
    
    print(f"Done. Generated {flag_num - 1000} rule groups", file=sys.stderr)
    print(f"Output: {out_path}", file=sys.stderr)

if __name__ == '__main__':
    main()
